# 必要パッケージのインストール

In [103]:
import pandas as pd
import numpy as np

In [104]:
rois_in_image = 60
images = 90
row_num = rois_in_image * images

# ot2_ypd/Results.csvからnormalized_ot2-ypd.csvを出力

## ディレクトリ・ファイルの取得

In [105]:
cd /mnt/d/github_repo

/mnt/d/github_repo

In [106]:
target_dir = "automatic_spotassay/"
filename = "quantification_with_imageJ/ot2_ypd/Results.csv"
path = target_dir + filename
csv=pd.read_csv(path)

In [107]:
df=csv[0:row_num]['Mean'].to_frame()

## 加工

In [108]:
df['executer']="ot2"

In [109]:
df['agar']="YPD"

In [110]:
df['timepoint']=0

In [111]:
df[3820:3830]

         Mean executer agar  timepoint
3820  134.676      ot2  YPD          0
3821  131.488      ot2  YPD          0
3822  130.336      ot2  YPD          0
3823  122.075      ot2  YPD          0
3824  103.472      ot2  YPD          0
3825  132.593      ot2  YPD          0
3826  129.160      ot2  YPD          0
3827  125.750      ot2  YPD          0
3828  115.188      ot2  YPD          0
3829  104.648      ot2  YPD          0

In [112]:
spot_num_in_image = 60 #image一枚につき、どれだけのspotを登録したか
spot_num_in_plate = 30
spot_num_in_serial = 5

In [113]:
for i in range(int(len(df)/spot_num_in_image)):
    df['timepoint'][0+i*spot_num_in_image:spot_num_in_image+i*spot_num_in_image]=1+i

/tmp/ipykernel_8759/2984097721.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['timepoint'][0+i*spot_num_in_image:spot_num_in_image+i*spot_num_in_image]=1+i

In [114]:
df['plate']=1

In [115]:
for i in range(int(len(df)/spot_num_in_image)):
    df['plate'][0+i*spot_num_in_image:spot_num_in_plate+i*spot_num_in_image]=1
    df['plate'][spot_num_in_plate+i*spot_num_in_image:spot_num_in_image+i*spot_num_in_image]=2

/tmp/ipykernel_8759/1204716180.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['plate'][0+i*spot_num_in_image:spot_num_in_plate+i*spot_num_in_image]=1
/tmp/ipykernel_8759/1204716180.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['plate'][spot_num_in_plate+i*spot_num_in_image:spot_num_in_image+i*spot_num_in_image]=2

In [116]:
df['serial_num']=0

In [117]:
for i in range(int(len(df)/spot_num_in_plate)):
    df['serial_num'][0+i*spot_num_in_plate:spot_num_in_serial+i*spot_num_in_plate]=1
    df['serial_num'][spot_num_in_serial+i*spot_num_in_plate:2*spot_num_in_serial+i*spot_num_in_plate]=2
    df['serial_num'][2*spot_num_in_serial+i*spot_num_in_plate:3*spot_num_in_serial+i*spot_num_in_plate]=3
    df['serial_num'][3*spot_num_in_serial+i*spot_num_in_plate:4*spot_num_in_serial+i*spot_num_in_plate]=4
    df['serial_num'][4*spot_num_in_serial+i*spot_num_in_plate:5*spot_num_in_serial+i*spot_num_in_plate]=5
    df['serial_num'][5*spot_num_in_serial+i*spot_num_in_plate:6*spot_num_in_serial+i*spot_num_in_plate]=6

/tmp/ipykernel_8759/3438398293.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][0+i*spot_num_in_plate:spot_num_in_serial+i*spot_num_in_plate]=1
/tmp/ipykernel_8759/3438398293.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][spot_num_in_serial+i*spot_num_in_plate:2*spot_num_in_serial+i*spot_num_in_plate]=2
/tmp/ipykernel_8759/3438398293.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][2*spot_num_in_serial+i*spot_num_in_plate:3*spot_num_in_serial+i*spot_num_in_plate]=3
/tmp/ipykernel_8759/3438398293.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][3*spot_num_in_serial+i*spot_num_in_plate:4*spot_num_in_serial+i*spot_num_in_plate]=4
/tmp/ipykernel_8759/3438398293.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][4*spot_num_in_serial+i*spot_num_in_plate:5*spot_num_in_serial+i*spot_num_in_plate]=5
/tmp/ipykernel_8759/3438398293.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][5*spot_num_in_serial+i*spot_num_in_plate:6*spot_num_in_serial+i*spot_num_in_plate]=6

In [118]:
df['spot']=0

In [119]:
for i in range(int(len(df)/spot_num_in_serial)):
    df['spot'][0+i*spot_num_in_serial]=1
    df['spot'][1+i*spot_num_in_serial]=2
    df['spot'][2+i*spot_num_in_serial]=3
    df['spot'][3+i*spot_num_in_serial]=4
    df['spot'][4+i*spot_num_in_serial]=5

/tmp/ipykernel_8759/3189110617.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spot'][0+i*spot_num_in_serial]=1
/tmp/ipykernel_8759/3189110617.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spot'][1+i*spot_num_in_serial]=2
/tmp/ipykernel_8759/3189110617.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spot'][2+i*spot_num_in_serial]=3
/tmp/ipykernel_8759/3189110617.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spot'][3+i*spot_num_in_serial]=4
/tmp/ipykernel_8759/3189110617.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spot'][4+i*spot_num_in_serial]=5

In [120]:
df['normalized']=float(0)

In [121]:
for i in range(int(len(df))):
  df['normalized'][i] = df['Mean'][i]/df['Mean'][i%60]

/tmp/ipykernel_8759/2500417561.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['normalized'][i] = df['Mean'][i]/df['Mean'][i%60]

In [122]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5400 entries, 0 to 5399
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Mean        5400 non-null   float64
 1   executer    5400 non-null   object
 2   agar        5400 non-null   object
 3   timepoint   5400 non-null   int64
 4   plate       5400 non-null   int64
 5   serial_num  5400 non-null   int64
 6   spot        5400 non-null   int64
 7   normalized  5400 non-null   float64
dtypes: float64(2), int64(4), object(2)
memory usage: 337.6+ KB
None

In [123]:
df

         Mean executer agar  timepoint  plate  serial_num  spot  normalized
0      77.206      ot2  YPD          1      1           1     1    1.000000
1      76.971      ot2  YPD          1      1           1     2    1.000000
2      76.995      ot2  YPD          1      1           1     3    1.000000
3      77.085      ot2  YPD          1      1           1     4    1.000000
4      77.370      ot2  YPD          1      1           1     5    1.000000
...       ...      ...  ...        ...    ...         ...   ...         ...
5395  131.596      ot2  YPD         90      2           6     1    1.690379
5396  130.769      ot2  YPD         90      2           6     2    1.717639
5397  128.928      ot2  YPD         90      2           6     3    1.697158
5398  128.769      ot2  YPD         90      2           6     4    1.695936
5399   98.168      ot2  YPD         90      2           6     5    1.253966

[5400 rows x 8 columns]

##   csvに出力

In [124]:
target_dir

'automatic_spotassay/'

In [125]:
df.to_csv(target_dir + 'data_analysis/ot2_ypd_normalized.csv')

# ot2_ypdtm/Results.csvからnormalized_ot2-ypdtm.csvを出力

##  ディレクトリ・ファイルの取得

In [126]:
target_dir = "automatic_spotassay/"
filename = "quantification_with_imageJ/ot2_ypdtm/Results.csv"
path = target_dir + filename
csv=pd.read_csv(path)

In [127]:
df=csv[0:row_num]['Mean'].to_frame()

##  加工

In [128]:
df['executer']="ot2"

In [129]:
df['agar']="YPD-TM"

In [130]:
df['timepoint']=0

In [131]:
df[3820:3830]

         Mean executer    agar  timepoint
3820  113.340      ot2  YPD-TM          0
3821  110.917      ot2  YPD-TM          0
3822   98.490      ot2  YPD-TM          0
3823   86.518      ot2  YPD-TM          0
3824   80.476      ot2  YPD-TM          0
3825   81.210      ot2  YPD-TM          0
3826   81.118      ot2  YPD-TM          0
3827   80.269      ot2  YPD-TM          0
3828   79.499      ot2  YPD-TM          0
3829   79.360      ot2  YPD-TM          0

In [132]:
spot_num_in_image = 60 #image一枚につき、どれだけのspotを登録したか
spot_num_in_plate = 30
spot_num_in_serial = 5

In [133]:
for i in range(int(len(df)/spot_num_in_image)):
    df['timepoint'][0+i*spot_num_in_image:spot_num_in_image+i*spot_num_in_image]=1+i

/tmp/ipykernel_8759/2984097721.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['timepoint'][0+i*spot_num_in_image:spot_num_in_image+i*spot_num_in_image]=1+i

In [134]:
df['plate']=1

In [135]:
for i in range(int(len(df)/spot_num_in_image)):
    df['plate'][0+i*spot_num_in_image:spot_num_in_plate+i*spot_num_in_image]=1
    df['plate'][spot_num_in_plate+i*spot_num_in_image:spot_num_in_image+i*spot_num_in_image]=2

/tmp/ipykernel_8759/1204716180.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['plate'][0+i*spot_num_in_image:spot_num_in_plate+i*spot_num_in_image]=1
/tmp/ipykernel_8759/1204716180.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['plate'][spot_num_in_plate+i*spot_num_in_image:spot_num_in_image+i*spot_num_in_image]=2

In [136]:
df['serial_num']=0

In [137]:
for i in range(int(len(df)/spot_num_in_plate)):
    df['serial_num'][0+i*spot_num_in_plate:spot_num_in_serial+i*spot_num_in_plate]=1
    df['serial_num'][spot_num_in_serial+i*spot_num_in_plate:2*spot_num_in_serial+i*spot_num_in_plate]=2
    df['serial_num'][2*spot_num_in_serial+i*spot_num_in_plate:3*spot_num_in_serial+i*spot_num_in_plate]=3
    df['serial_num'][3*spot_num_in_serial+i*spot_num_in_plate:4*spot_num_in_serial+i*spot_num_in_plate]=4
    df['serial_num'][4*spot_num_in_serial+i*spot_num_in_plate:5*spot_num_in_serial+i*spot_num_in_plate]=5
    df['serial_num'][5*spot_num_in_serial+i*spot_num_in_plate:6*spot_num_in_serial+i*spot_num_in_plate]=6

/tmp/ipykernel_8759/3438398293.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][0+i*spot_num_in_plate:spot_num_in_serial+i*spot_num_in_plate]=1
/tmp/ipykernel_8759/3438398293.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][spot_num_in_serial+i*spot_num_in_plate:2*spot_num_in_serial+i*spot_num_in_plate]=2
/tmp/ipykernel_8759/3438398293.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][2*spot_num_in_serial+i*spot_num_in_plate:3*spot_num_in_serial+i*spot_num_in_plate]=3
/tmp/ipykernel_8759/3438398293.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][3*spot_num_in_serial+i*spot_num_in_plate:4*spot_num_in_serial+i*spot_num_in_plate]=4
/tmp/ipykernel_8759/3438398293.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][4*spot_num_in_serial+i*spot_num_in_plate:5*spot_num_in_serial+i*spot_num_in_plate]=5
/tmp/ipykernel_8759/3438398293.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][5*spot_num_in_serial+i*spot_num_in_plate:6*spot_num_in_serial+i*spot_num_in_plate]=6

In [138]:
df['spot']=0

In [139]:
for i in range(int(len(df)/spot_num_in_serial)):
    df['spot'][0+i*spot_num_in_serial]=1
    df['spot'][1+i*spot_num_in_serial]=2
    df['spot'][2+i*spot_num_in_serial]=3
    df['spot'][3+i*spot_num_in_serial]=4
    df['spot'][4+i*spot_num_in_serial]=5

/tmp/ipykernel_8759/3189110617.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spot'][0+i*spot_num_in_serial]=1
/tmp/ipykernel_8759/3189110617.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spot'][1+i*spot_num_in_serial]=2
/tmp/ipykernel_8759/3189110617.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spot'][2+i*spot_num_in_serial]=3
/tmp/ipykernel_8759/3189110617.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spot'][3+i*spot_num_in_serial]=4
/tmp/ipykernel_8759/3189110617.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spot'][4+i*spot_num_in_serial]=5

In [140]:
df['normalized']=float(1)

In [141]:
for i in range(int(len(df))):
  df['normalized'][i] = df['Mean'][i]/df['Mean'][i%60]

/tmp/ipykernel_8759/2500417561.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['normalized'][i] = df['Mean'][i]/df['Mean'][i%60]

In [142]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5400 entries, 0 to 5399
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Mean        5400 non-null   float64
 1   executer    5400 non-null   object
 2   agar        5400 non-null   object
 3   timepoint   5400 non-null   int64
 4   plate       5400 non-null   int64
 5   serial_num  5400 non-null   int64
 6   spot        5400 non-null   int64
 7   normalized  5400 non-null   float64
dtypes: float64(2), int64(4), object(2)
memory usage: 337.6+ KB
None

In [143]:
df

        Mean executer    agar  timepoint  plate  serial_num  spot  normalized
0     76.825      ot2  YPD-TM          1      1           1     1    1.000000
1     75.303      ot2  YPD-TM          1      1           1     2    1.000000
2     74.980      ot2  YPD-TM          1      1           1     3    1.000000
3     75.113      ot2  YPD-TM          1      1           1     4    1.000000
4     76.459      ot2  YPD-TM          1      1           1     5    1.000000
...      ...      ...     ...        ...    ...         ...   ...         ...
5395  81.992      ot2  YPD-TM         90      2           6     1    1.042386
5396  80.049      ot2  YPD-TM         90      2           6     2    1.036018
5397  79.783      ot2  YPD-TM         90      2           6     3    1.036978
5398  79.943      ot2  YPD-TM         90      2           6     4    1.029663
5399  78.705      ot2  YPD-TM         90      2           6     5    1.017084

[5400 rows x 8 columns]

##  csvに出力

In [144]:
target_dir

'automatic_spotassay/'

In [145]:
df.to_csv(target_dir + 'data_analysis/ot2_ypdtm_normalized.csv')

# human_ypd/Results.csvからnormalized_human-ypd.csvを出力

## ディレクトリ・ファイルの取得

In [146]:
target_dir = "automatic_spotassay/"
filename = "quantification_with_imageJ/human_ypd/Results.csv"
path = target_dir + filename
csv=pd.read_csv(path)

In [147]:
df=csv[0:row_num]['Mean'].to_frame()

## 加工

In [148]:
df['executer']="human"

In [149]:
df['agar']="YPD"

In [150]:
df['timepoint']=0

In [151]:
spot_num_in_image = 60 #image一枚につき、どれだけのspotを登録したか
spot_num_in_plate = 30
spot_num_in_serial = 5

In [152]:
for i in range(int(len(df)/spot_num_in_image)):
    df['timepoint'][0+i*spot_num_in_image:spot_num_in_image+i*spot_num_in_image]=1+i

/tmp/ipykernel_8759/2984097721.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['timepoint'][0+i*spot_num_in_image:spot_num_in_image+i*spot_num_in_image]=1+i

In [153]:
df['plate']=1

In [154]:
for i in range(int(len(df)/spot_num_in_image)):
    df['plate'][0+i*spot_num_in_image:spot_num_in_plate+i*spot_num_in_image]=1
    df['plate'][spot_num_in_plate+i*spot_num_in_image:spot_num_in_image+i*spot_num_in_image]=2

/tmp/ipykernel_8759/1204716180.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['plate'][0+i*spot_num_in_image:spot_num_in_plate+i*spot_num_in_image]=1
/tmp/ipykernel_8759/1204716180.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['plate'][spot_num_in_plate+i*spot_num_in_image:spot_num_in_image+i*spot_num_in_image]=2

In [155]:
df['serial_num']=0

In [156]:
for i in range(int(len(df)/spot_num_in_plate)):
    df['serial_num'][0+i*spot_num_in_plate:spot_num_in_serial+i*spot_num_in_plate]=1
    df['serial_num'][spot_num_in_serial+i*spot_num_in_plate:2*spot_num_in_serial+i*spot_num_in_plate]=2
    df['serial_num'][2*spot_num_in_serial+i*spot_num_in_plate:3*spot_num_in_serial+i*spot_num_in_plate]=3
    df['serial_num'][3*spot_num_in_serial+i*spot_num_in_plate:4*spot_num_in_serial+i*spot_num_in_plate]=4
    df['serial_num'][4*spot_num_in_serial+i*spot_num_in_plate:5*spot_num_in_serial+i*spot_num_in_plate]=5
    df['serial_num'][5*spot_num_in_serial+i*spot_num_in_plate:6*spot_num_in_serial+i*spot_num_in_plate]=6

/tmp/ipykernel_8759/3438398293.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][0+i*spot_num_in_plate:spot_num_in_serial+i*spot_num_in_plate]=1
/tmp/ipykernel_8759/3438398293.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][spot_num_in_serial+i*spot_num_in_plate:2*spot_num_in_serial+i*spot_num_in_plate]=2
/tmp/ipykernel_8759/3438398293.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][2*spot_num_in_serial+i*spot_num_in_plate:3*spot_num_in_serial+i*spot_num_in_plate]=3
/tmp/ipykernel_8759/3438398293.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][3*spot_num_in_serial+i*spot_num_in_plate:4*spot_num_in_serial+i*spot_num_in_plate]=4
/tmp/ipykernel_8759/3438398293.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][4*spot_num_in_serial+i*spot_num_in_plate:5*spot_num_in_serial+i*spot_num_in_plate]=5
/tmp/ipykernel_8759/3438398293.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][5*spot_num_in_serial+i*spot_num_in_plate:6*spot_num_in_serial+i*spot_num_in_plate]=6

In [157]:
df['spot']=0

In [158]:
for i in range(int(len(df)/spot_num_in_serial)):
    df['spot'][0+i*spot_num_in_serial]=1
    df['spot'][1+i*spot_num_in_serial]=2
    df['spot'][2+i*spot_num_in_serial]=3
    df['spot'][3+i*spot_num_in_serial]=4
    df['spot'][4+i*spot_num_in_serial]=5

/tmp/ipykernel_8759/3189110617.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spot'][0+i*spot_num_in_serial]=1
/tmp/ipykernel_8759/3189110617.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spot'][1+i*spot_num_in_serial]=2
/tmp/ipykernel_8759/3189110617.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spot'][2+i*spot_num_in_serial]=3
/tmp/ipykernel_8759/3189110617.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spot'][3+i*spot_num_in_serial]=4
/tmp/ipykernel_8759/3189110617.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spot'][4+i*spot_num_in_serial]=5

In [159]:
df['normalized']=float(1)

In [160]:
for i in range(int(len(df))):
  df['normalized'][i] = df['Mean'][i]/df['Mean'][i%60]

/tmp/ipykernel_8759/2500417561.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['normalized'][i] = df['Mean'][i]/df['Mean'][i%60]

In [161]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5400 entries, 0 to 5399
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Mean        5400 non-null   float64
 1   executer    5400 non-null   object
 2   agar        5400 non-null   object
 3   timepoint   5400 non-null   int64
 4   plate       5400 non-null   int64
 5   serial_num  5400 non-null   int64
 6   spot        5400 non-null   int64
 7   normalized  5400 non-null   float64
dtypes: float64(2), int64(4), object(2)
memory usage: 337.6+ KB
None

In [162]:
df

         Mean executer agar  timepoint  plate  serial_num  spot  normalized
0      76.994    human  YPD          1      1           1     1    1.000000
1      76.458    human  YPD          1      1           1     2    1.000000
2      76.290    human  YPD          1      1           1     3    1.000000
3      76.216    human  YPD          1      1           1     4    1.000000
4      76.255    human  YPD          1      1           1     5    1.000000
...       ...      ...  ...        ...    ...         ...   ...         ...
5395  125.901    human  YPD         90      2           6     1    1.598398
5396  124.776    human  YPD         90      2           6     2    1.634820
5397  125.238    human  YPD         90      2           6     3    1.643004
5398  124.718    human  YPD         90      2           6     4    1.628109
5399   87.674    human  YPD         90      2           6     5    1.111739

[5400 rows x 8 columns]

## csvに出力

In [163]:
target_dir

'automatic_spotassay/'

In [164]:
df.to_csv(target_dir + '/data_analysis/human_ypd_normalized.csv')

# human_ypdtm/Results.csvからnormalized_human-ypdtm.csvを出力

## ディレクトリ・ファイルの取得

In [165]:
target_dir = "automatic_spotassay/"
filename = "quantification_with_imageJ/human_ypdtm/Results.csv"
path = target_dir + filename
csv=pd.read_csv(path)

In [166]:
df=csv[0:row_num]['Mean'].to_frame()

## 加工

In [167]:
df['executer']="human"

In [168]:
df['agar']="YPD-TM"

In [169]:
df['timepoint']=0

In [170]:
spot_num_in_image = 60 #image一枚につき、どれだけのspotを登録したか
spot_num_in_plate = 30
spot_num_in_serial = 5

In [171]:
for i in range(int(len(df)/spot_num_in_image)):
    df['timepoint'][0+i*spot_num_in_image:spot_num_in_image+i*spot_num_in_image]=1+i

/tmp/ipykernel_8759/2984097721.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['timepoint'][0+i*spot_num_in_image:spot_num_in_image+i*spot_num_in_image]=1+i

In [172]:
df['plate']=1

In [173]:
for i in range(int(len(df)/spot_num_in_image)):
    df['plate'][0+i*spot_num_in_image:spot_num_in_plate+i*spot_num_in_image]=1
    df['plate'][spot_num_in_plate+i*spot_num_in_image:spot_num_in_image+i*spot_num_in_image]=2

/tmp/ipykernel_8759/1204716180.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['plate'][0+i*spot_num_in_image:spot_num_in_plate+i*spot_num_in_image]=1
/tmp/ipykernel_8759/1204716180.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['plate'][spot_num_in_plate+i*spot_num_in_image:spot_num_in_image+i*spot_num_in_image]=2

In [174]:
df['serial_num']=0

In [175]:
for i in range(int(len(df)/spot_num_in_plate)):
    df['serial_num'][0+i*spot_num_in_plate:spot_num_in_serial+i*spot_num_in_plate]=1
    df['serial_num'][spot_num_in_serial+i*spot_num_in_plate:2*spot_num_in_serial+i*spot_num_in_plate]=2
    df['serial_num'][2*spot_num_in_serial+i*spot_num_in_plate:3*spot_num_in_serial+i*spot_num_in_plate]=3
    df['serial_num'][3*spot_num_in_serial+i*spot_num_in_plate:4*spot_num_in_serial+i*spot_num_in_plate]=4
    df['serial_num'][4*spot_num_in_serial+i*spot_num_in_plate:5*spot_num_in_serial+i*spot_num_in_plate]=5
    df['serial_num'][5*spot_num_in_serial+i*spot_num_in_plate:6*spot_num_in_serial+i*spot_num_in_plate]=6

/tmp/ipykernel_8759/3438398293.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][0+i*spot_num_in_plate:spot_num_in_serial+i*spot_num_in_plate]=1
/tmp/ipykernel_8759/3438398293.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][spot_num_in_serial+i*spot_num_in_plate:2*spot_num_in_serial+i*spot_num_in_plate]=2
/tmp/ipykernel_8759/3438398293.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][2*spot_num_in_serial+i*spot_num_in_plate:3*spot_num_in_serial+i*spot_num_in_plate]=3
/tmp/ipykernel_8759/3438398293.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][3*spot_num_in_serial+i*spot_num_in_plate:4*spot_num_in_serial+i*spot_num_in_plate]=4
/tmp/ipykernel_8759/3438398293.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][4*spot_num_in_serial+i*spot_num_in_plate:5*spot_num_in_serial+i*spot_num_in_plate]=5
/tmp/ipykernel_8759/3438398293.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['serial_num'][5*spot_num_in_serial+i*spot_num_in_plate:6*spot_num_in_serial+i*spot_num_in_plate]=6

In [176]:
df['spot']=0

In [177]:
for i in range(int(len(df)/spot_num_in_serial)):
    df['spot'][0+i*spot_num_in_serial]=1
    df['spot'][1+i*spot_num_in_serial]=2
    df['spot'][2+i*spot_num_in_serial]=3
    df['spot'][3+i*spot_num_in_serial]=4
    df['spot'][4+i*spot_num_in_serial]=5

/tmp/ipykernel_8759/3189110617.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spot'][0+i*spot_num_in_serial]=1
/tmp/ipykernel_8759/3189110617.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spot'][1+i*spot_num_in_serial]=2
/tmp/ipykernel_8759/3189110617.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spot'][2+i*spot_num_in_serial]=3
/tmp/ipykernel_8759/3189110617.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spot'][3+i*spot_num_in_serial]=4
/tmp/ipykernel_8759/3189110617.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spot'][4+i*spot_num_in_serial]=5

In [178]:
df['normalized']=float(1)

In [179]:
for i in range(int(len(df))):
  df['normalized'][i] = df['Mean'][i]/df['Mean'][i%60]

/tmp/ipykernel_8759/2500417561.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['normalized'][i] = df['Mean'][i]/df['Mean'][i%60]

In [180]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5400 entries, 0 to 5399
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Mean        5400 non-null   float64
 1   executer    5400 non-null   object
 2   agar        5400 non-null   object
 3   timepoint   5400 non-null   int64
 4   plate       5400 non-null   int64
 5   serial_num  5400 non-null   int64
 6   spot        5400 non-null   int64
 7   normalized  5400 non-null   float64
dtypes: float64(2), int64(4), object(2)
memory usage: 337.6+ KB
None

In [181]:
df

        Mean executer    agar  timepoint  plate  serial_num  spot  normalized
0     79.487    human  YPD-TM          1      1           1     1    1.000000
1     79.584    human  YPD-TM          1      1           1     2    1.000000
2     79.825    human  YPD-TM          1      1           1     3    1.000000
3     80.027    human  YPD-TM          1      1           1     4    1.000000
4     79.617    human  YPD-TM          1      1           1     5    1.000000
...      ...      ...     ...        ...    ...         ...   ...         ...
5395  80.516    human  YPD-TM         90      2           6     1    0.999541
5396  74.689    human  YPD-TM         90      2           6     2    1.005601
5397  74.124    human  YPD-TM         90      2           6     3    1.005644
5398  73.019    human  YPD-TM         90      2           6     4    1.002100
5399  71.590    human  YPD-TM         90      2           6     5    0.992803

[5400 rows x 8 columns]

## csvに出力

In [182]:
target_dir

'automatic_spotassay/'

In [183]:
df.to_csv(target_dir + 'data_analysis/human_ypdtm_normalized.csv')

# データをまとめる

In [184]:
target_dir = "automatic_spotassay/data_analysis/"

In [185]:
df_ot2ypd=pd.read_csv(target_dir + "ot2_ypd_normalized.csv", index_col=0)
df_ot2ypdtm=pd.read_csv(target_dir + "ot2_ypdtm_normalized.csv", index_col=0)
df_humanypd=pd.read_csv(target_dir + "human_ypd_normalized.csv", index_col=0)
df_humanypdtm=pd.read_csv(target_dir + "human_ypdtm_normalized.csv", index_col=0)

In [186]:
df_ot2ypd

         Mean executer agar  timepoint  plate  serial_num  spot  normalized
0      77.206      ot2  YPD          1      1           1     1    1.000000
1      76.971      ot2  YPD          1      1           1     2    1.000000
2      76.995      ot2  YPD          1      1           1     3    1.000000
3      77.085      ot2  YPD          1      1           1     4    1.000000
4      77.370      ot2  YPD          1      1           1     5    1.000000
...       ...      ...  ...        ...    ...         ...   ...         ...
5395  131.596      ot2  YPD         90      2           6     1    1.690379
5396  130.769      ot2  YPD         90      2           6     2    1.717639
5397  128.928      ot2  YPD         90      2           6     3    1.697158
5398  128.769      ot2  YPD         90      2           6     4    1.695936
5399   98.168      ot2  YPD         90      2           6     5    1.253966

[5400 rows x 8 columns]

In [187]:
df_sum = pd.concat([df_ot2ypd,df_ot2ypdtm,df_humanypd,df_humanypdtm], axis=0, ignore_index=True)

In [188]:
df_sum.to_csv(target_dir + 'summary_ot2ypd-ot2ypdtm-humanypd-humanypdtm.csv')